# Generated by Django 5.1.15 on 2026-08-08 20:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esims", "0010_esim_account_ownership"),
        ("organizations", "0003_organization_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_external_id",
                    models.CharField(
                        db_index=True,
                        help_text="RoamKit-issued opaque device key (not a client authz signal).",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unbound", "Unbound"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("unbound_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bound_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_bindings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "esim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_bindings",
                        to="esims.esim",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_bindings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="organizations.devicebinding",
                    ),
                ),
                (
                    "unbound_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_bindings_unbound",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device binding",
                "verbose_name_plural": "device bindings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceBindingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("bind", "Bind"),
                            ("unbind", "Unbind"),
                            ("rebind", "Rebind"),
                        ],
                        max_length=16,
                    ),
                ),
                ("device_external_id", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_binding_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="organizations.devicebinding",
                    ),
                ),
                (
                    "esim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_binding_events",
                        to="esims.esim",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_binding_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "previous_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by_events",
                        to="organizations.devicebinding",
                    ),
                ),
            ],
            options={
                "verbose_name": "device binding event",
                "verbose_name_plural": "device binding events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="devicebinding",
            index=models.Index(
                fields=["organization", "status"], name="org_dbind_org_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicebinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("esim",),
                name="organizations_devicebinding_one_active_per_esim",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicebinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("organization", "device_external_id"),
                name="organizations_devicebinding_one_active_device_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicebinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "unbound", "replaced"])),
                name="organizations_devicebinding_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="devicebindingevent",
            index=models.Index(
                fields=["organization", "created_at"], name="org_dbevt_org_created"
            ),
        ),
    ]
