# Generated by Django 5.1.15 on 2026-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_device_binding"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicebinding",
            name="credential_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hex of device credential; plaintext never stored.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="devicebinding",
            name="credential_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicebindingevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("bind", "Bind"),
                    ("unbind", "Unbind"),
                    ("rebind", "Rebind"),
                    ("credential_issue", "Credential issue"),
                    ("credential_rotate", "Credential rotate"),
                ],
                max_length=32,
            ),
        ),
    ]
