# Generated by Django 5.1.15 on 2026-07-25 09:17

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_accounts(apps, schema_editor):
    """Create a zero-balance Account for every existing user."""
    User = apps.get_model("accounts", "User")
    Account = apps.get_model("billing", "Account")
    for user in User.objects.all().iterator():
        Account.objects.get_or_create(
            user_id=user.pk,
            defaults={
                "id": uuid.uuid4(),
                "balance": Decimal("0"),
                "version": 0,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_billing_schema"),
        ("esims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delta", models.DecimalField(decimal_places=6, max_digits=20)),
                ("balance_after", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("order", "Order"),
                            ("topup", "Top-up"),
                            ("subscription", "Subscription"),
                            ("refund", "Refund"),
                            ("admin_adjustment", "Admin adjustment"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("reference_id", models.CharField(db_index=True, max_length=64)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="billing.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit ledger entry",
                "verbose_name_plural": "credit ledger entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "amount_credited",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wallet_connect", "WalletConnect"),
                            ("cex_manual", "CEX manual"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("raw_rpc_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_requests",
                        to="billing.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "deposit request",
                "verbose_name_plural": "deposit requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_per_period",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("next_billing_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="billing.account",
                    ),
                ),
                (
                    "esim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="esims.esim",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="billing_account_balance_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 0)),
                name="billing_account_version_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="creditledgerentry",
            index=models.Index(
                fields=["account", "created_at"], name="billing_cre_account_363a7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditledgerentry",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="billing_cre_referen_b61d5c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("delta", 0), _negated=True),
                name="billing_ledger_delta_ne_0",
            ),
        ),
        migrations.AddIndex(
            model_name="depositrequest",
            index=models.Index(
                fields=["account", "status"], name="billing_dep_account_1317a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="depositrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_requested__gt", 0)),
                name="billing_deposit_amount_requested_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_credited__isnull", True),
                    ("amount_credited__gt", 0),
                    _connector="OR",
                ),
                name="billing_deposit_amount_credited_null_or_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["account", "status"], name="billing_sub_account_0905ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "next_billing_date"],
                name="billing_sub_status_440b85_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_period__gt", 0)),
                name="billing_subscription_price_per_period_gt_0",
            ),
        ),
        migrations.RunPython(backfill_accounts, migrations.RunPython.noop),
    ]
