# Generated by Django 5.1.15 on 2026-07-27 07:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_billing_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditledgerentry",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("order", "Order"),
                    ("topup", "Top-up"),
                    ("subscription", "Subscription"),
                    ("refund", "Refund"),
                    ("admin_adjustment", "Admin adjustment"),
                    ("voucher", "Voucher"),
                ],
                db_index=True,
                help_text="Domain object that caused this ledger entry (deposit, order, …).",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="VoucherCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shared code when redemption_mode=shared (normalized uppercase).",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "redemption_mode",
                    models.CharField(
                        choices=[("shared", "Shared"), ("unique", "Unique")],
                        default="shared",
                        max_length=16,
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("promo", "Promo"),
                            ("gift", "Gift"),
                            ("admin", "Admin"),
                            ("partner", "Partner"),
                        ],
                        default="promo",
                        max_length=16,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("fixed_credit", "Fixed credit"),
                            ("percent_bonus", "Percent bonus"),
                            ("free_subscription", "Free subscription"),
                            ("free_topup", "Free top-up"),
                        ],
                        default="fixed_credit",
                        max_length=32,
                    ),
                ),
                ("credit_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "max_redemptions_total",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_redemptions_per_account",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fraud", "Fraud"),
                            ("expired_campaign", "Expired campaign"),
                            ("manual_revoke", "Manual revoke"),
                            ("duplicate_issue", "Duplicate issue"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "issued_by_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("admin", "Admin"),
                            ("partner", "Partner"),
                            ("api", "API"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                (
                    "issued_by_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "voucher campaign",
                "verbose_name_plural": "voucher campaigns",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("credit_amount__gt", 0)),
                        name="billing_voucher_campaign_credit_amount_gt_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_redemptions_total__isnull", True),
                            ("max_redemptions_total__gt", 0),
                            _connector="OR",
                        ),
                        name="billing_voucher_campaign_max_total_null_or_gt_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_redemptions_per_account__isnull", True),
                            ("max_redemptions_per_account__gt", 0),
                            _connector="OR",
                        ),
                        name="billing_voucher_campaign_max_per_account_null_or_gt_0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VoucherBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "issued_by_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("admin", "Admin"),
                            ("partner", "Partner"),
                            ("api", "API"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                (
                    "issued_by_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="billing.vouchercampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "voucher batch",
                "verbose_name_plural": "voucher batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "redemption_mode",
                    models.CharField(
                        choices=[("shared", "Shared"), ("unique", "Unique")],
                        default="unique",
                        max_length=16,
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("promo", "Promo"),
                            ("gift", "Gift"),
                            ("admin", "Admin"),
                            ("partner", "Partner"),
                        ],
                        default="gift",
                        max_length=16,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("fixed_credit", "Fixed credit"),
                            ("percent_bonus", "Percent bonus"),
                            ("free_subscription", "Free subscription"),
                            ("free_topup", "Free top-up"),
                        ],
                        default="fixed_credit",
                        max_length=32,
                    ),
                ),
                ("credit_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fraud", "Fraud"),
                            ("expired_campaign", "Expired campaign"),
                            ("manual_revoke", "Manual revoke"),
                            ("duplicate_issue", "Duplicate issue"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "issued_by_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("admin", "Admin"),
                            ("partner", "Partner"),
                            ("api", "API"),
                        ],
                        default="system",
                        max_length=16,
                    ),
                ),
                (
                    "issued_by_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="billing.voucherbatch",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="billing.vouchercampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "voucher",
                "verbose_name_plural": "vouchers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("ledger_entry_id", models.UUIDField(blank=True, null=True)),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("redeemed_at", models.DateTimeField()),
                (
                    "redeemed_ip",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "redeemed_user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_redemptions",
                        to="billing.account",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="billing.vouchercampaign",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="billing.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "voucher redemption",
                "verbose_name_plural": "voucher redemptions",
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="voucherbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gt", 0)),
                name="billing_voucher_batch_size_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="voucher",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_amount__gt", 0)),
                name="billing_voucher_credit_amount_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="voucherredemption",
            index=models.Index(
                fields=["account", "campaign"], name="billing_vou_account_6ae8e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucherredemption",
            index=models.Index(
                fields=["account", "voucher"], name="billing_vou_account_f511c0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherredemption",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="billing_voucher_redemption_amount_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherredemption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("campaign__isnull", True), ("voucher__isnull", False)),
                    models.Q(("campaign__isnull", False), ("voucher__isnull", True)),
                    _connector="OR",
                ),
                name="billing_voucher_redemption_exactly_one_source",
            ),
        ),
    ]
