# Generated by Django 5.1.15 on 2026-10-08 02:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

PARTNER_LEDGER_TYPES = (
    "partner_margin",
    "partner_grant_out",
    "partner_grant_in",
)


def _noop_forward(apps, schema_editor):
    """Ledger reference types are choices on an existing CharField. No backfill."""


def reverse_partner_ledger_reference_types(apps, schema_editor):
    """Stop if any ledger row uses a partner reference type. Never delete rows."""
    CreditLedgerEntry = apps.get_model("billing", "CreditLedgerEntry")
    if CreditLedgerEntry.objects.filter(
        reference_type__in=PARTNER_LEDGER_TYPES
    ).exists():
        raise RuntimeError(
            "Cannot reverse partner channel schema while ledger rows use "
            "partner_margin, partner_grant_out, or partner_grant_in"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_account_kind"),
        ("organizations", "0007_fleet_serial_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditledgerentry",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("order", "Order"),
                    ("topup", "Top-up"),
                    ("subscription", "Subscription"),
                    ("refund", "Refund"),
                    ("admin_adjustment", "Admin adjustment"),
                    ("voucher", "Voucher"),
                    ("partner_margin", "Partner margin"),
                    ("partner_grant_out", "Partner grant out"),
                    ("partner_grant_in", "Partner grant in"),
                ],
                db_index=True,
                help_text="Domain object that caused this ledger entry (deposit, order, …).",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PartnerChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "revenue_share_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_channel",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner channel",
                "verbose_name_plural": "partner channels",
            },
        ),
        migrations.CreateModel(
            name="CustomerAttributionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("changed_by_user_id_snapshot", models.UUIDField()),
                ("change_reason", models.TextField()),
                ("changed_at", models.DateTimeField()),
                ("previous_attributed_at", models.DateTimeField()),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_attribution_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_attribution_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_partner_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribution_history_from",
                        to="billing.partnerchannel",
                    ),
                ),
                (
                    "to_partner_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribution_history_to",
                        to="billing.partnerchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer attribution history",
                "verbose_name_plural": "customer attribution histories",
            },
        ),
        migrations.CreateModel(
            name="CustomerAttribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("invite_link", "Invite link"), ("admin", "Admin")],
                        max_length=16,
                    ),
                ),
                (
                    "invite_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("attributed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_attribution",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_attributions",
                        to="billing.partnerchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer attribution",
                "verbose_name_plural": "customer attributions",
            },
        ),
        migrations.CreateModel(
            name="PartnerCreditGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_user_id_snapshot", models.UUIDField()),
                ("granted_by_user_id_snapshot", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credit_ledger_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_grant_credit",
                        to="billing.creditledgerentry",
                    ),
                ),
                (
                    "customer_attribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_grants",
                        to="billing.customerattribution",
                    ),
                ),
                (
                    "customer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_credit_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debit_ledger_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_grant_debit",
                        to="billing.creditledgerentry",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_grants_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_grants",
                        to="billing.partnerchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner credit grant",
                "verbose_name_plural": "partner credit grants",
            },
        ),
        migrations.CreateModel(
            name="PartnerInviteLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("regenerated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "partner_channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invite_link",
                        to="billing.partnerchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner invite link",
                "verbose_name_plural": "partner invite links",
            },
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="invite_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributions",
                to="billing.partnerinvitelink",
            ),
        ),
        migrations.CreateModel(
            name="PartnerMarginAccrual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_user_id_snapshot", models.UUIDField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("topup", "Top-up"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("list_price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("net_price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("margin", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "revenue_share_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("partner_share", models.DecimalField(decimal_places=6, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_attribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="margin_accruals",
                        to="billing.customerattribution",
                    ),
                ),
                (
                    "customer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_margin_accruals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_margin_accrual",
                        to="billing.creditledgerentry",
                    ),
                ),
                (
                    "partner_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="margin_accruals",
                        to="billing.partnerchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner margin accrual",
                "verbose_name_plural": "partner margin accruals",
            },
        ),
        migrations.CreateModel(
            name="PendingPartnerAttribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invite_token_snapshot", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_attributions",
                        to="billing.partnerchannel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_partner_attribution",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pending partner attribution",
                "verbose_name_plural": "pending partner attributions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRenewalCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("billing_date", models.DateField()),
                (
                    "renewal_list_price_usd",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "renewal_net_price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("renewed", "Renewed"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renewal_cycles",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription renewal cycle",
                "verbose_name_plural": "subscription renewal cycles",
            },
        ),
        migrations.AddConstraint(
            model_name="partnerchannel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revenue_share_percent__gte", 0),
                    ("revenue_share_percent__lte", 100),
                ),
                name="billing_partner_channel_share_range",
            ),
        ),
        migrations.AddIndex(
            model_name="customerattributionhistory",
            index=models.Index(
                fields=["user", "changed_at"], name="bill_attr_history_user_at"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercreditgrant",
            index=models.Index(
                fields=["partner_channel", "created_at"], name="bill_grant_chan_created"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercreditgrant",
            index=models.Index(
                fields=["partner_channel", "customer_user"],
                name="bill_grant_chan_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnercreditgrant",
            constraint=models.UniqueConstraint(
                fields=("partner_channel", "idempotency_key"),
                name="billing_partner_grant_idem_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnercreditgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="billing_partner_grant_amount_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="customerattribution",
            index=models.Index(
                fields=["partner_channel", "attributed_at"],
                name="bill_attr_chan_attributed",
            ),
        ),
        migrations.AddIndex(
            model_name="partnermarginaccrual",
            index=models.Index(
                fields=["partner_channel", "created_at"],
                name="bill_accrual_chan_created",
            ),
        ),
        migrations.AddIndex(
            model_name="partnermarginaccrual",
            index=models.Index(
                fields=["partner_channel", "customer_user"],
                name="bill_accrual_chan_customer",
            ),
        ),
        migrations.AddIndex(
            model_name="partnermarginaccrual",
            index=models.Index(fields=["customer_user"], name="bill_accrual_customer"),
        ),
        migrations.AddConstraint(
            model_name="partnermarginaccrual",
            constraint=models.UniqueConstraint(
                fields=("source_type", "source_id"),
                name="billing_partner_accrual_source_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingpartnerattribution",
            index=models.Index(fields=["expires_at"], name="bill_pending_attr_expires"),
        ),
        migrations.AddConstraint(
            model_name="subscriptionrenewalcycle",
            constraint=models.UniqueConstraint(
                fields=("subscription", "billing_date"),
                name="billing_renewal_cycle_sub_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionrenewalcycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "paused", "failed"])),
                fields=("subscription",),
                name="billing_renewal_one_unfinished",
            ),
        ),
        migrations.RunPython(
            _noop_forward,
            reverse_partner_ledger_reference_types,
        ),
    ]
