# Generated by Django 5.1.15 on 2026-10-08 14:44

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_partner_user_id_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerinvitelink",
            name="bonus_amount",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.000000"), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="partnerinvitelink",
            name="campaign",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="partnerinvitelink",
            name="content",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="partnerinvitelink",
            name="name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="partnerinvitelink",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="partnerinvitelink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="partnerinvitelink",
            name="partner_channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invite_links",
                to="billing.partnerchannel",
            ),
        ),
        migrations.AlterField(
            model_name="partnerinvitelink",
            name="token",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name="partnerinvitelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("bonus_amount__gte", 0)),
                name="billing_invite_link_bonus_gte_0",
            ),
        ),
    ]
