# Generated by Django 5.1.15 on 2026-10-08 14:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_partner_invite_link_many"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "utm_content",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invite_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="billing.partnerinvitelink",
                    ),
                ),
            ],
            options={
                "verbose_name": "invite visit",
                "verbose_name_plural": "invite visits",
                "indexes": [
                    models.Index(
                        fields=["invite_link", "created_at"],
                        name="bill_invite_visit_link_at",
                    )
                ],
            },
        ),
    ]
