# Generated by Django 5.1.15 on 2026-10-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_invite_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerattribution",
            name="bonus_amount_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="invite_campaign_snapshot",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="invite_content_snapshot",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="invite_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="invite_source_snapshot",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="invite_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_attributions",
                to="billing.invitevisit",
            ),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="registered_via_invite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="utm_campaign_snapshot",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="utm_content_snapshot",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="utm_medium_snapshot",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="customerattribution",
            name="utm_source_snapshot",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="pendingpartnerattribution",
            name="invite_visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_attributions",
                to="billing.invitevisit",
            ),
        ),
    ]
