# Generated by Django 5.1.15 on 2026-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_attribution_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditledgerentry",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("order", "Order"),
                    ("topup", "Top-up"),
                    ("subscription", "Subscription"),
                    ("refund", "Refund"),
                    ("admin_adjustment", "Admin adjustment"),
                    ("voucher", "Voucher"),
                    ("partner_margin", "Partner margin"),
                    ("partner_grant_out", "Partner grant out"),
                    ("partner_grant_in", "Partner grant in"),
                    ("partner_invite_bonus", "Partner invite bonus"),
                ],
                db_index=True,
                help_text="Domain object that caused this ledger entry (deposit, order, …).",
                max_length=32,
            ),
        ),
    ]
