# Generated by Django 5.1.15 on 2026-07-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
