# Generated by Django 5.1.15 on 2026-08-05 18:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_voucher_admin_audit"),
        ("wallet", "0002_deposit_observation"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositobservation",
            name="shadow_only",
            field=models.BooleanField(
                default=False,
                help_text="ADR 018 shadow dual-path — compare only; never grant Credits.",
            ),
        ),
        migrations.CreateModel(
            name="ShadowDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("legacy_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("legacy_account_id", models.UUIDField()),
                ("legacy_tx_hash", models.CharField(max_length=66)),
                (
                    "shadow_amount",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("shadow_account_id", models.UUIDField(blank=True, null=True)),
                (
                    "shadow_observation_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("shadow_would_credit", models.BooleanField(default=False)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("different", "Different"),
                            ("error", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deposit_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_decision",
                        to="billing.depositrequest",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shadow_decisions",
                        to="wallet.depositobservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "shadow decision",
                "verbose_name_plural": "shadow decisions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["outcome", "severity"], name="wallet_shadow_outcome_sev"
                    ),
                    models.Index(fields=["created_at"], name="wallet_shadow_created"),
                ],
            },
        ),
    ]
