# Generated by Django 5.1.15 for Faza 2 esims

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Esim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iccid",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("lpa", models.CharField(blank=True, max_length=255)),
                ("matching_id", models.CharField(blank=True, max_length=128)),
                ("qrcode", models.TextField(blank=True)),
                ("qrcode_url", models.URLField(blank=True, max_length=512)),
                (
                    "direct_apple_installation_url",
                    models.URLField(blank=True, max_length=1024),
                ),
                ("manual_installation", models.TextField(blank=True)),
                ("qrcode_installation", models.TextField(blank=True)),
                (
                    "installation_guide_url",
                    models.URLField(blank=True, max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "Unused"),
                            ("active", "Active"),
                            ("exhausted", "Exhausted"),
                            ("expired", "Expired"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unused",
                        max_length=32,
                    ),
                ),
                ("usage_remaining_mb", models.IntegerField(blank=True, null=True)),
                ("usage_total_mb", models.IntegerField(blank=True, null=True)),
                ("usage_status", models.CharField(blank=True, max_length=64)),
                ("usage_is_unlimited", models.BooleanField(blank=True, null=True)),
                ("usage_expired_at", models.DateTimeField(blank=True, null=True)),
                ("usage_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esims",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"],
                        name="esims_esim_user_id_fa9b9a_idx",
                    )
                ],
            },
        ),
    ]
