# Generated by Django 5.1.15 on 2026-07-25 13:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_billing_schema"),
        ("esims", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_external_id", models.CharField(db_index=True, max_length=64)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fulfilling", "Fulfilling"),
                            ("fulfilled", "Fulfilled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="fulfilling",
                        max_length=32,
                    ),
                ),
                (
                    "external_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topups",
                        to="billing.account",
                    ),
                ),
                (
                    "esim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topups",
                        to="esims.esim",
                    ),
                ),
            ],
            options={
                "verbose_name": "top-up",
                "verbose_name_plural": "top-ups",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "status"],
                        name="esims_topup_account_273603_idx",
                    ),
                    models.Index(
                        fields=["esim", "status"], name="esims_topup_esim_id_adaac0_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="esims_topup_amount_gt_0",
                    )
                ],
            },
        ),
    ]
