# Generated by Django 5.1.15 on 2026-10-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esims", "0011_esim_matching_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="topup",
            name="net_price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text=(
                    "Wholesale net at top-up creation (ADR 023). "
                    "Write-once. Null is never backfilled."
                ),
                max_digits=20,
                null=True,
            ),
        ),
    ]
