# Generated by Django 5.1.15 on 2026-07-25 09:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_accounts(apps, schema_editor):
    """Point each Order at its owner's billing Account."""
    Order = apps.get_model("orders", "Order")
    Account = apps.get_model("billing", "Account")
    for order in Order.objects.all().iterator():
        account = Account.objects.get(user_id=order.user_id)
        order.account_id = account.pk
        order.save(update_fields=["account_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_billing_schema"),
        ("catalog", "0004_location_coverages"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="billing.account",
            ),
        ),
        migrations.RunPython(backfill_order_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="billing.account",
            ),
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_user_id_02a211_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["account", "status"], name="orders_orde_account_611ca4_idx"
            ),
        ),
    ]
